repos:
  - repo: local
    hooks:
      - id: make-lint-fix
        name: Run make lint-fix
        entry: make lint-fix
        language: system
        pass_filenames: false
        always_run: true